df <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?", colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'))
df <- df[df$Date %in% c("1/2/2007","2/2/2007"),]
df <- df[complete.cases(df),]
dateTime <- strptime(paste(df$Date, df$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
df <- cbind(dateTime, df)
par(mfrow = c(2,2), oma = c(0,0,2,0), mar = c(4,4,2,1))
plot(df$Global_active_power ~ df$dateTime, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(df$Voltage ~ df$dateTime, type = "l", ylab = "Voltage (volt)", xlab = "")
plot(df$dateTime, df$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(df$dateTime, df$Sub_metering_2, type="l", col="red")
lines(df$dateTime, df$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
plot(df$Global_reactive_power ~ df$dateTime, type = "l", ylab = "Voltage (volt)", xlab = "")
dev.copy(png,"plot4.png", width=480, height=480)
dev.off()